smoke_test: false
env_config:
  tickers:
    - ADAUSD
    - BTCUSD
    - CRVUSD
    - ETHUSD
    - FTTUSD
    - LTCUSD
    - XRPUSD
  env: ShrinkEnv
  start_date: '2021-01-01'
  end_date: '2022-05-01'
  warmup: '${eval: 24*7}'
  rebalance_freq: '${eval: 24*7}'
  data_freq: 1
  freq_unit: h
  init_cash: 100000
  txn_cost: 0.001
  mu_method: hist
  shrinkage_target: Identity
  obs_type: returns # or prices
use_custom_model: true
custom_model_config:
  name: SimpleTorchRNNModel
model_config:
  # below does not apply for custom model
  use_attention: false
  use_lstm: true
  lstm_cell_size: 32
  lstm_use_prev_action: false
  lstm_use_prev_reward: false
  fcnet_hiddens:
    - 64
    - 64
training_iterations: 10000
checkpoint_freq: 100
algorithm: PPO
training_args:
  gamma: 0.98
  lr: 0.001
  train_batch_size: 32000
  sgd_minibatch_size: 4096
resources_args:
  num_gpus: 1
rollouts_args:
  num_rollout_workers: 32
  num_envs_per_worker: 8

