notes: ???
smoke_test: false
env_config:
  tickers:
    - ADAUSD
    - BTCUSD
    - CRVUSD
    - ETHUSD
    - FTTUSD
    - LTCUSD
    - XRPUSD
  env: ShrinkEnv
  start_date: '2021-01-01'
  end_date: '2022-05-01'
  warmup: '${eval: 24*7}'
  rebalance_freq: '${eval: 24*7}'
  data_freq: 1
  freq_unit: h
  init_cash: 100000
  txn_cost: 0.001
  mu_method: hist
  shrinkage_target: Identity
  obs_type: returns # or prices
use_custom_model: false
custom_model_config:
  name: TorchRNN1
model_config:
  # below does not apply for custom model
  max_seq_len: 24
  use_attention: false
  use_lstm: true
  lstm_cell_size: 32
  lstm_use_prev_action: false
  lstm_use_prev_reward: false
  fcnet_hiddens:
    - 64
    - 64
training_iterations: 1000
checkpoint_freq: 5
algorithm: ppo
training_args:
  gamma: 0.98
  lr: 0.001
#  train_batch_size: 16384
#  sgd_minibatch_size: 1024
# resources_args:
#   num_gpus: 0.3
#   num_gpus_per_worker: 0.3
#   num_gpus_per_learner_worker: 0.3
# rollouts_args:
#   num_rollout_workers: 1
#   num_envs_per_worker: 1

